### ISSUE TITLE
Atualizar "Ajuda - Fontes de Dados" com descrição sobre o Datasus

### ISSUE THREAD

**Issue by FredericoVieira** [DataViva/dataviva-site#1529]

**Comment by FredericoVieira** [comment]
Departamento de Informática do SUS – DATASUS

Ministério da Saúde - MS

O DATASUS disponibiliza informações que podem servir para subsidiar análises objetivas da situação sanitária, tomadas de decisão baseadas em evidências e elaboração de programas de ações de saúde. Uma das competências do departamento é manter o acervo das bases de dados necessários ao sistema de informações em saúde e aos sistemas internos de gestão institucional. 

As bases compreendem os dados Sistema de Informações Ambulatoriais do SUS, Sistema de informações de Mortalidade, Sistema de Comunicação de Informação Hospitalar, Sistema de Comunicação de Informação Hospitalar e Ambulatorial, Sistema de informação de Nascidos Vivos, Sistema de Monitoramento e Avaliação do Pré-Natal, Parto, Puerpério e Criança, Cadastro Nacional de Estabelecimentos de Saúde, Arquivos com a base territorial (municípios, regiões de saúde, territórios da cidadania etc.) em uso para a Disseminação de Informações de Saúde, assim como mapas e arquivos de conversão para uso pelo TabWin e Tabnet. Arquivos com a distribuição da população brasileira segundo censos demográficos, contagens populacionais e estimativas, desde 1980, por município, sexo e idade, e segundo as estimativas realizadas para o TCU, desde 1992, por município.
 
A partir dos dados da base CNES do DATASUS, o DataViva apresenta informações anuais dos estabelecimentos de saúde brasileiros, de 2008 em diante. As principais variáveis são: código nacional do estabelecimento de saúde, região de saúde, vínculo com o SUS, esfera Administrativa, tipo de leito/especialidade, tipo de equipamento, tipo de estabelecimentos e entre outros. O nível de agregação, em termos geográficos, pode ser feito por unidades da federação, mesorregiões, microrregiões e municípios.

Acesso em: http://www2.datasus.gov.br/DATASUS/index.php?area=0901&item=1

**Comment by eltonfreitas** [comment]
SUS IT Department – DATASUS
Ministry of Health – MH
DATASUS makes available information that may subsidize an objective analysis of the health situation, the decision-making based on evidences and the making of health action programs. One of the department’s competencies is to keep the database collection needed for the information system in health and to the internal systems of institutional management.
The database consists of data from SUS Ambulatory Information System; Mortality Information System; Hospital Information Communication System; Hospital and Ambulatory Information Communication System; Live birth Information System; Pre-Natal, Childbirth, Puerperium and Child Monitoring and Evaluation System; National Registry of Health Establishments; Files with territorial base – municipality, health regions, citizenship territories, etc. – in use for the Health Information Dissemination; as well as maps and conversion files for TabWin and Tabnet use. Files with the Brazilian population distribution according to demographic census, population counts and estimations since 1980 by municipality, sex and age, and according to estimations made for TCU – The Brazilian Federal Court of Accounts – since 1992, by municipality.
Using the CNES database of DATASUS, DataViva shows annual information of Brazilian health establishments from 2008 onwards. The main variables are Health Establishment National Code, Health region, SUS linking, Administrative sphere, type of hospital bed/specialty, equipment type, establishment type, among other variables. The aggregation level in geographical terms can be done by federal unit, mesoregion, microregion and municipality.
Access on: http://www2.datasus.gov.br/DATASUS/index.php?area=0901&item=1
