### ISSUE TITLE
Vocational Course Profile

### ISSUE THREAD

**Issue by guilhermesganserla** [DataViva/dataviva-site#209]
Now we have seven profiles in the developing DataViva, one of then being "Universities". After thinking about it we think that it would be more interesting to have universities info as a filter for "High Education Courses" as they are from the same database and are complementary informations. Furthermore, we believe that having a specific profile for the "Vocational School" would also be interesting, making this data easier to find in the platform.

**Comment by davelandry** [comment]
We are going to have apps related to Universities in the Higher Education Course Profiles, but having a combination Profile with both a University and Course selected isn't currently possible with the current codebase.

Because of this, we think there should still be a University Profile. It would show the courses offered by that University, as well as help with the SEO of the site.

On the main topic of a Vocational School Profile:
We are assuming a "Vocational School" is any school in the school census dataset that offers a vocational course, whether they offer other basic education or not. I've uploaded a list of these schools, ordered by total enrollment, to Google Docs: https://docs.google.com/spreadsheets/d/1qa_3XjI8vZpBAj6vzQlT7sPeQDx0s8jLQpQFtA3V2iQ/edit?usp=sharing

This list shows that a lot of the names are poor quality. There are a lot of duplicate names, abbreviations, and some entries in ALL CAPS. If you believe this list is fine to display, we will use it. If you'd like to make edits to the names, use that document and we will update our database.

**Comment by guilhermesganserla** [comment]
The most important thing is to show the data of enrolment, studing, graduates, etc for a region so we can show the number of people joining the label force. Assuming that we don't need to show the name of the schools, we just need to show how many people are enrolled per course per locality, so we wouldn't use the names of the sochools, just the data per locality.

**Comment by davelandry** [comment]
If that is the case, then this data should be shown on the location Profile pages, not a separate Profile page for each School.

**Comment by guilhermesganserla** [comment]
We can do a Profile for professional courses where the main info is the course not the school

**Comment by davelandry** [comment]
What specific apps could you see being on this page?

**Comment by guilhermesganserla** [comment]
For example:

After o choose a course you would be able to see:

- A Tree Map showing where we have this kind of course;
- A line plot showing the evolution of the number of enroled people;
- A Geo Map with the same info of Trre Map, showing the distribution of the courses.
