### ISSUE TITLE
Make click-zooming more apparent in Stacked and Line

### ISSUE THREAD

**Issue by guilhermesganserla** [DataViva/dataviva-site#221]
In the Tree Map for Vocational School Enrolment we have two Depth options, "Field" and "Course". 
![image](https://cloud.githubusercontent.com/assets/7582295/6027221/daae52ca-abc7-11e4-9197-a6be5374fe25.png)
We should also have it for the others apps to maintain the pattern
![image](https://cloud.githubusercontent.com/assets/7582295/6027241/f2d29faa-abc7-11e4-85a5-90c70b5e9ca6.png)

**Comment by davelandry** [comment]
The Stacked and Line Plots function slightly differently, as we require users to click a line/area in order to zoom into that specific area. We should include text in the title that indicates they can "click to zoom".

We do this because drawing a Line or Stacked app, for all years, with > 500 data points takes a while to render on the page and is very illegible. By forcing the user to zoom into only a specific grouping, it makes the apps much easier to use.
