### ISSUE TITLE
Shortening growth labels in dropdown menus

### ISSUE THREAD

**Issue by alexandersimoes** [DataViva/dataviva-site#227]
How do you guys feel about shortening the text that appears in these dropdown menus so that they don't take up so much space. For example instead of "Nominal Annual Export Growth Rate (1 year)" We could just say "Growth (1 year)" and "Growth (5 year)" since we no longer have growth values only growth rates.

![screen shot 2015-02-06 at 12 28 05 pm](https://cloud.githubusercontent.com/assets/252276/6084048/9f7ecaaa-adfb-11e4-9e06-27cdb25ed941.png)

from http://dv2.datawheel.us/apps/embed/tree_map/secex/2pe/all/all/hs/

**Comment by davelandry** [comment]
We would still need to list what variable the growth is based on, for example in RAIS we have both: "Employee Growth Rate" and "Wage Growth Rate".

That being said, I still think we should remove the words "Nominal Annual".

**Comment by guilhermesganserla** [comment]
Guys I agree that there are too many words and that we should make the names smaller but by putting out the name "Nominal" we can lead the user to misunderstand the information we are giving because people that use this kind of rate usually uses the real rate, that being the nominal one deflated. So to let the information clear I think we should use "Nominal Growth (1 Year)" instead od " Nominal Annual Export Growth Rate (1 Year)". This way we make the names smaller and still be clear of what we are showing, what do you guys think?

**Comment by davelandry** [comment]
Sounds good, we'll implement this for the next update.
