### ISSUE TITLE
Geo Map bug

### ISSUE THREAD

**Issue by guilhermesganserla** [DataViva/dataviva-site#235]
The Geo Map is not working properly. If you choose "Espírito Santo! the map is on the left and there the Capital is in the middle of the ocean.

![image](https://cloud.githubusercontent.com/assets/7582295/6133123/ea78c416-b13e-11e4-9cdf-84b07e06f6ea.png)

http://dv2.datawheel.us/apps/builder/geo_map/secex/4es/all/all/bra/?color=export_val&controls=true&year=2013

**Comment by davelandry** [comment]
Nice find! This is happening because that is an actual island that is part of Espirito Santo: http://en.wikipedia.org/wiki/Trindade_and_Martim_Vaz

This also happens for Pernambuco because of this island: http://en.wikipedia.org/wiki/Fernando_de_Noronha

We'll clean that up. Let us know if you can find any other cases like this.
