### ISSUE TITLE
Missing vocational courses

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#246]
there are about 235 Vocational Courses, in 13 categories, but we can´t find them in the profiles. Elton liked a lot the University colors and solution, may you could do something similar for Vocational…

**Comment by davelandry** [comment]
We do have icons and colors for all of the Vocational Course categories, but only 4 of them are actually present in the data.

Unless we have aggregated the data incorrectly, this is all we will be able to show.

**Comment by dgomes2004** [comment]
It should be on the data, better check with @eltonfreitas .

**Comment by eltonfreitas** [comment]
I checked in database here, there are all categories.

**Comment by jspeis** [comment]
Seems like a bug with the data aggregation with 4 vs 5 digits, we'll fix that and update the tables.

**Comment by jspeis** [comment]
The database has now been updated with course IDs that were 4 digits. You may see some of the courses here:

http://dv2.datawheel.us/profiles/course_sc/01/?app=2
http://dv2.datawheel.us/profiles/course_sc/04/?app=2
http://dv2.datawheel.us/profiles/course_sc/09/?app=2

You may need to clear your browser cache in order to see the updated vocational course list in the selector.
