### ISSUE TITLE
Incorrect domestic ECI calculation

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#269]
Guys,

according to @eltonfreitas , we have a mistake on the calculation:

"or represented as a share:
exports = [0.8, 0.2]
Now using the PCI values for these products by multiplying them by the share of that product in that location's basket:" (from the wiki)

We should use the share considering not the location, but the products share for Brazil.

@eltonfreitas , am I right?

**Comment by eltonfreitas** [comment]
![image](https://cloud.githubusercontent.com/assets/6808970/6669141/1c0cf716-cbd6-11e4-9c87-2f3a7169bc59.png)

**Comment by alexandersimoes** [comment]
@eltonfreitas, I'm not sure this makes sense to use RCA values here since they are continuous values and have to inherent range i.e. they could be anything from 0 to infinity. After doing this calculation for the states of brazil in 2014, here are the values I get --

| bra_id |ECI   |
|-----|----------------------|
| 1ac | -836.0017280514705   |
| 2rn | -371.5211656777117   |
| 2pb | -259.7487524471329   |
| 2pi | -159.37578704734443  |
| 1ap | -68.32020159893965   |
| 2ce | -58.38681731195867   |
| 2se | -40.26035599796517   |
| 2al | -31.65130027078606   |
| 1rr | -30.15829043601349   |
| 1ro | -22.37064069174064   |
| 2ma | -19.543073194050166  |
| 4rj | -14.925773837749581  |
| 1pa | -10.520134539398045  |
| 4es | -4.972940270793025   |
| 4mg | -4.920735994996023   |
| 1to | -4.529966120880529   |
| 3mt | -4.032722501871469   |
| 3go | -4.022833162735476   |
| 2ba | -3.2757163014786457  |
| 3ms | -1.9819279196154511  |
| 5rs | -1.8498744908007803  |
| 5pr | -0.5452727823165896  |
| 4sp | -0.08794044834249576 |
| 5sc | 2.241019492625407    |
| 3df | 2.952702206029894    |
| 2pe | 10.660094028916223   |
| 0xx | 19.90945468028396    |
| 1am | 21.83637369219402    |

**Comment by eltonfreitas** [comment]
@alexandersimoes, I think this is strange result. For example, how to **1ac** the result was **-836.0017**? The formula uses PCI, that range usually (-4,4); RCA, that is a binary variable (1 or 0); and a ratio of export of a product in a location by exports of that same product in for all Brazil, this value is between 0 and 1.

Furthermore all, **1ac** is the state of Acre, a small state that should not have many products with RCA and the share of its exports in relation to Brazil is too small. The ranking makes any sense, but it was expected that São Paulo was the state with the highest ECI because of exports a lot of product with RCA and the shares of exportations in relation to all Brazil is high.

Please, check 2 things. First, if RCA have only values 1 or 0. The second, if the share the exports is exports of a product p of specific location l by exports of same product p of all Brazil. Other thing, not necessary use **0xx** for this calculations, maybe this can generate some distortion.

**Comment by alexandersimoes** [comment]
Ok I hadn't realized you wanted to use the binary RCA. I've made that change. I've also excluded 0xx now and here are the results -- 

|state|ECI|
|-----|----------------------|
| 2ba | -26.591475186990664  |
| 1pa | -21.8596686258385    |
| 5sc | -13.333974600757097  |
| 2ce | -12.8371915371793    |
| 3mt | -9.950537624562926   |
| 4mg | -8.640939498194365   |
| 5pr | -8.160638644271353   |
| 2rn | -7.6419246922980015  |
| 3go | -7.328127103619895   |
| 1ro | -5.244872665440304   |
| 4es | -4.96015839951724    |
| 2pe | -4.623188003813554   |
| 3ms | -4.0956803151585195  |
| 2pb | -3.6750003451059725  |
| 1to | -2.374785525683359   |
| 2pi | -1.8683041512954393  |
| 2ma | -1.4207647081610326  |
| 1ap | -0.8049232819619583  |
| 3df | -0.5323672932731974  |
| 1rr | -0.4750112212516625  |
| 2al | -0.2153095783185287  |
| 2se | -0.093412267870409   |
| 1ac | -0.06010383897278739 |
| 5rs | -0.02587353062982023 |
| 1am | 5.49270588988252     |
| 4rj | 15.627713833424991   |
| 4sp | 124.4393347069604    |

**Comment by eltonfreitas** [comment]
These results have improved. Although surprising the very high value of São Paulo (**124.4393**), this may have happened to use the domestic RCA. 

Anyway, this corroborates to show the gap between São Paulo and other States. Perhaps with international RCA values are lower, but still the ranking will look like this.

**Comment by alexandersimoes** [comment]
@dgomes2004 are you ok with me adding this to the DB for this thursday's update?

**Comment by dgomes2004** [comment]
Is this done? Can we close it?
