### ISSUE TITLE
Confusing "students" column name

### ISSUE THREAD

**Issue by dgomes2004** [DataViva/dataviva-site#297]
Guys,

looking at the data app, there is a data column which makes no sense. For the student status, we only have 3 categories: enrolled (are studying), graduates (just finished), entrants (just entered). The next column (students) should not exist, since there is no such information.

http://dv2.datawheel.us/data/hedu/2010/4mg/00575/show.6/?order=enrolled.desc

**Comment by davelandry** [comment]
The column "students" is not an error. It is the number of students registered at the school, whether or not they are enrolled in any classes.

Would it be more clear if we changed the name to "Registered Students" or something similar?

**Comment by dgomes2004** [comment]
Dave, according to @eltonfreitas this number of students registered is not necessary, since it is just an control of students ID, they may have left school or transfered to another. So the best thing here is to not show this info, ok?

**Comment by eltonfreitas** [comment]
Is it, as Dave says "*number of students registered at the school, whether or not they are enrolled in any classes*". We could change this name, but as we have no means to reach this number in MEC, it turns out to be unnecessary. If other variables of SC data be used, such as, number of transfer, desertion, etc. this information would be more helpful.
