### ISSUE TITLE
Add HS2 product aggregations into database

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#308]
We only have now section and position, it's lacking "chapter". This no longer existed?

http://dv2.datawheel.us/apps/builder/tree_map/secex/all/all/all/hs/?controls=true

**Comment by dgomes2004** [comment]
Treemaps are not showing HS middle level on depth filter. In fact, I didn´t find HS4 anywhere.

**Comment by davelandry** [comment]
We cannot show chapters because we do not have chapter data aggregated in the database (see #295).

@dgomes2004, the position level products are HS4. Here is the mapping:
* Section = 2-digit category
* Chapter = 4-digit HS2
* Position = 6-digit HS4

Each product ID has the Section ID added to the beginning of it's ID.

**Comment by dgomes2004** [comment]
Yes, I meant Chapter, as commented on #295 .

Reopening for consideration, ok?

**Comment by dgomes2004** [comment]
Not possible. Will let it here for future consideration after launch (DataViva 3.0)
