### ISSUE TITLE
SECEX data for 2014 not showing

### ISSUE THREAD

**Issue by eltonfreitas** [DataViva/dataviva-site#341]
![image](https://cloud.githubusercontent.com/assets/6808970/7715796/af3876ec-fe61-11e4-9499-1fb83a615f4d.png)

**Comment by davelandry** [comment]
This seems to only be happening when loading all years, correct?

**Comment by alexandersimoes** [comment]
If you look at the timeline you'll notice 1999 appears which we don't have data for and 2014 doesn't appear signaling to me that all the years are probably off by one i.e. t-1.

**Comment by davelandry** [comment]
For future reference: this was an issue introduced in v1.7.2 of d3plus. The javascript Date parser has trouble parsing simple years (ex. "1994") correctly. It offsets the value by the client's timezone, so what we were getting was late in the night of December 31, 1993, instead of the expected January 1, 1994. This is fixed by formatting the date values as "1994/01/01".
